export const globalLocalization = {
    ru: {
        cars: 'Транспорт',
        carsTypeShort: {
            cargo: 'Груз',
            passenger: 'Пасс',
            specialized: 'Спец',
        },
        carsTypeLong: {
            cargo: 'Грузовой',
            passenger: 'Пассажирский',
            specialized: 'Специализированный',
        },
        settings: 'Настройки',
        lang: 'Русский',
        transportUnloaded: 'Упс! Не удалось загрузить данные',
        changeLang: 'Сменить язык на:',
        developer: 'Приложение разработано Георгием Зибровским',
        viewTypes: {
            map: 'Карта',
            list: 'Список',
        },
        ymap: 'ru_Ru',
        mapIsLoading: 'Загрузка карты..',
        info: 'Инфо',
        call: 'Позвонить',
        write: 'Написать',
        whatsappText: 'Добрый день, какой ночер заказа у вас сейчас в работе?',
        networkError: 'Упс! Данные не загрузились, проблема решается, продолжите на iOS',
        noFreeCars: 'Нет свободных машин',
    },
    en: {
        cars: 'Cars',
        carsTypeShort: {
            cargo: 'Cargo',
            passenger: 'Pass',
            specialized: 'Spec',
        },
        carsTypeLong: {
            cargo: 'Cargo',
            passenger: 'Passenger',
            specialized: 'Specialized',
        },
        settings: 'Settings',
        lang: 'English',
        transportUnloaded: 'Oops! Failed to load data',
        changeLang: 'Change language to:',
        developer: 'The application was developed by Georgy Zibrovsky',
        viewTypes: {
            map: 'Map',
            list: 'List',
        },
        ymap: 'en_En',
        mapIsLoading: 'Loading..',
        info: 'Info',
        call: 'Call',
        write: 'Write',
        whatsappText: 'Hello, what order date are you currently working on?',
        networkError: 'Oops! The data did not load, the problem is solved, try it on iOS',
        noFreeCars: 'No free cars',
    },
}